spring.application.name=tech-challenge
spring.datasource.url=jdbc:postgresql://localhost:5432/oficina
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=64656661756c747365637265746b65796d75737462657374726f6e6765727468616e74686973313233343536
security.jwt.expiration=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
